### ISSUE TITLE
base pug structure

### ISSUE THREAD

**Issue by marianzburlea** [catezee/grace-girls#1]
include header/header should be moved on top of h1 line
those two link tags in the head tag are one and the same with the content of include font-family/font-family
the idea is to keep only one, you can pick and choose whichever you want to keep
I'd keep the include font-family/font-family (in the head tag) as it looks cleaner 
![image](https://user-images.githubusercontent.com/1318985/42322162-513174be-8053-11e8-8346-9dd588a3530e.png)

**Comment by catezee** [comment]
If I put the header at the bottom, the header on my home page gets registered at the bottom of the home page.

**Comment by catezee** [comment]
Never mind. I've finally figured it out! Thank you for all your help. Much appreciated.
