### ISSUE TITLE
match the cool-config block

### ISSUE THREAD

**Issue by marianzburlea** [catezee/grace-girls#2]
remove the head tag from girls with grace and add heading, description to the javascript part
![image](https://user-images.githubusercontent.com/1318985/42322356-057e4956-8054-11e8-8ca8-58ed76743f29.png)

**Comment by catezee** [comment]
Done!

**Comment by catezee** [comment]
I've also committed, too.

**Comment by catezee** [comment]
I've figured it out and committed! Thanks again for your help, Marian!
